sudo: required
services:
  - docker


before_install:
  - docker build -t chrismarsh/docker-react -f Dockerfile.dev .

script:
  - docker run chrismarsh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-880177873800"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS-ACCESS-KEY
  secret_access_key:
    secure: ""$AWS-SECRET-KEY"
